CREATE DATABASE IF NOT EXISTS `AuthDB`;
GRANT ALL PRIVILEGES ON AuthDB.* TO 'diracx'@'%';
FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS `AuthDB`;
USE AuthDB;
CREATE TABLE IF NOT EXISTS DeviceFlows (
    UserCode VARCHAR(255) PRIMARY KEY,
    Status ENUM('PENDING', 'ERROR', 'READY', 'DONE') DEFAULT 'PENDING',
    CreationTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ClientID VARCHAR(255),
    Scope VARCHAR(1024),
    DeviceCode VARCHAR(128) UNIQUE,
    IDToken JSON
);

CREATE TABLE IF NOT EXISTS AuthorizationFlows (
    UUID CHAR(36) PRIMARY KEY,
    Status ENUM('PENDING', 'ERROR', 'READY', 'DONE') DEFAULT 'PENDING',
    ClientID VARCHAR(255),
    CreationTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Scope VARCHAR(1024),
    CodeChallenge VARCHAR(255),
    CodeChallengeMethod VARCHAR(8),
    RedirectURI VARCHAR(255),
    Code VARCHAR(255),
    IDToken JSON
);

CREATE TABLE IF NOT EXISTS RefreshTokens (
    JTI CHAR(36) PRIMARY KEY,
    Status ENUM('CREATED', 'REVOKED') DEFAULT 'CREATED',
    CreationTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Scope VARCHAR(1024),
    Sub VARCHAR(1024),
    PreferredUsername VARCHAR(255)
);
