apiVersion: v1
kind: Secret
metadata:
  name: diracx-secrets
stringData:
{{ .Values.diracx.settings | toYaml | indent 2 }}
---
{{- if .Values.htcondor.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: condor-token
  namespace: {{ $ns }}
type: Opaque
stringData:
  CONDOR_TOKEN: {{ .Values.htcondor.token | quote }}
{{- end }}

